### ISSUE TITLE
Compatibility with .NET Core 3.1

### ISSUE THREAD

**Issue by chandrikashivanna** [microsoftgraph/msgraph-training-azurefunction-csharp#11]
Could you please let us know if this can be used in .NET Core 3.1, when I tried doing it I have got compatibility issues with libraries used as they are working with .NET 5?

**Comment by jasonjoh** [comment]
Yes. If you look at the commit history, this was updated to .NET 5 in May. Any version of the code before that was on 3.1. This was the last 3.1 version:

https://github.com/microsoftgraph/msgraph-training-azurefunction-csharp/tree/70b8dc0cff5ff3acb4942ca72f8582065370fd20
