### ISSUE TITLE
Help needed to replace secret from user stores to Key vault

### ISSUE THREAD

**Issue by AmitavaHazra** [microsoftgraph/msgraph-training-azurefunction-csharp#15]
Reference
https://docs.microsoft.com/en-us/graph/tutorials/azure-functions?tutorial-step=5

Update code
Configuration is read from the user secret store, which only applies to your development machine. Before you publish to Azure, you'll need to change where you store your configuration, and update the code in Program.cs accordingly.

Can you please help how can we updated this code while publishing it in Azure Function app. Required code for Azure key vault or any other way .

**Comment by jasonjoh** [comment]
This might be helpful: https://docs.microsoft.com/azure/app-service/app-service-key-vault-references.
