### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by thomps0** [microsoftgraph/msgraph-training-azurefunction-csharp#7]
**Where did you get the code?**

- [x] Downloaded from GitHub
- [ ] Downloaded from the [Microsoft Graph quick start tool](https://developer.microsoft.com/graph/quick-start)
- [x] Followed the tutorial from [Microsoft Graph tutorials](https://docs.microsoft.com/graph/tutorials)

**Describe the bug**
I've tried both following the tutorial, as well as downloading from GitHub and have what I believe is the same error that the other user posted. Currently can pull new messages, but on subscribing an email address I'm left with an "Object reference not set to an instance of an object" error. It fails out on azurefunctions.js:59 and does so every time.

Error on the web page is: Call to SetSubscription returned 500 "Internal Server Error"

Error in the console is: 
[2021-05-14T17:28:38.394Z] Executed 'Notify' (Succeeded, Id=6a4ec2e3-f68e-4a4e-aa28-431bcb4f75a5, Duration=4ms)
[2021-05-14T17:28:39.069Z] Executed 'SetSubscription' (Failed, Id=13cfe347-1cde-4e97-80b8-011ab221e9fc, Duration=1801ms)
[2021-05-14T17:28:39.071Z] System.Private.CoreLib: Exception while executing function: SetSubscription. Microsoft.Graph.Core: Object reference not set to an instance of an object.

**To Reproduce**

1. Go to Subscriptions
2. Enter an email address
3. Click Subscribe

**Expected behavior**
Should subscribe the email.

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Chrome, Firefox and Edge (happens in all browsers)

**Dependency versions**

- Authentication library (MSAL, etc.) version:
- Graph library (Graph SDK, REST library, etc.) version:

**Additional context**
Function Runtime Version: 3.0.15417.0
.NET SDK 5.0.202 (x64)
Running this from PowerShell using Azure Command Line
Editor: Visual Studio Code

**Comment by jasonjoh** [comment]
Thanks for the added detail @thomps0! Since you're using Visual Studio Code, could you set a breakpoint on SetSubscription and see exactly which line of code the error is coming from? It will explicitly return a 500 if it doesn't find the `webHookId`, `webHookSecret`, `tenantId`, or `apiFunctionId` config values. However, it looks like from your output that Microsoft.Graph.Core is the one throwing the error.

The other things to verify are:

- The email address you are entering matches the user's `userPrincipalName`. This isn't always the case, so it's worth verifying.
- The user's mailbox is hosted on Exchange Online.

**Comment by jasonjoh** [comment]
Well the error in azurefunctions.js is because the Azure Function is encountering an error. We need to figure out why. Can you put a breakpoint on the `Run` function in SetSubscription.cs and step through the repro?

**Comment by thomps0** [comment]
Thanks for the patience Jason, I actually had to run it in Visual Studio because the debugger in VSCode wouldn't launch. I stepped through and didn't see anything that stood out as Null that shouldn't have been. It fails out on this section of code in the SetSubscription.cs file (screenshot below). It picks up the webHookID, webHookSecret, tenantID, apiFunctionID and even finds my username.

![image](https://user-images.githubusercontent.com/45877444/118839953-f4ffaf80-b894-11eb-8206-3a69df0d01ca.png)

Not really sure what else to poke around in but if you want to see more screenshots just let me know.

**Comment by jasonjoh** [comment]
What does `subscription` look like prior to the call? Also, what version of Microsoft.Graph are you using?

**Comment by thomps0** [comment]
![image](https://user-images.githubusercontent.com/45877444/118853967-57ab7800-b8a2-11eb-9dc5-e905083c5adc.png)
Subscription values can be seen above in the screenshot.

Graph version is 3.8.0 and I've included all the dependent packages:
![image](https://user-images.githubusercontent.com/45877444/118854988-4c0c8100-b8a3-11eb-9733-e2de676cff48.png)

**Comment by jasonjoh** [comment]
Could you update Microsoft.Graph to latest release version 3.32.0 and retry? There was a bug in the SDK around subscriptions and invalid tokens: https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/145

**Comment by thomps0** [comment]
OK so I've updated to 3.32.0 and got a couple build errors I can't seem to work through (probably due to my lack of understanding of what everything is doing):
![image](https://user-images.githubusercontent.com/45877444/118880734-3063a380-b8c0-11eb-9929-80ebc8a15079.png)

Those are the two build errors now, and here are the referenced code blocks (both in Notify.cs):
![image](https://user-images.githubusercontent.com/45877444/118880829-525d2600-b8c0-11eb-98d8-356076a8c0b7.png)

![image](https://user-images.githubusercontent.com/45877444/118880883-643ec900-b8c0-11eb-9856-af0865f46827.png)

**Comment by jasonjoh** [comment]
Ah yes - this is because they introduced a `ChangeNotification` class in the SDK in recent updates. It wasn't there before. To fix this, rename the `ChangeNotification` class in the project to `ChangeNotificationPayload`. See https://github.com/microsoftgraph/msgraph-training-azurefunction-csharp/blob/refresh/demo/GraphTutorial/Models/ChangeNotificationPayload.cs

Also be sure to change the type in the `ProcessNotification` method to `ChangeNotificationPayload`.

**Comment by thomps0** [comment]
Ok - making progress now.  Different error in the Azure Function Debug Console, and I've been back over the permissions a few times to make sure I set them as in the tutorial but it's still kicking back a 500 error (at the same spot as before).

![image](https://user-images.githubusercontent.com/45877444/119150617-9c5b1e80-ba1c-11eb-9b58-fa81305827b9.png)

**Comment by jasonjoh** [comment]
Ok. So it sounds like the Graph service can't reach your Notify function to validate it. It won't create the subscription if the `NotificationUrl` isn't reachable and doesn't respond to a validation request. The function does this here:

https://github.com/microsoftgraph/msgraph-training-azurefunction-csharp/blob/70b8dc0cff5ff3acb4942ca72f8582065370fd20/demo/GraphTutorial/Notify.cs#L47-L56

Things to check:

- Is ngrok running? If so, do you see a validation request coming in (you can view requests at http://localhost:4040)?
- Does your `ngrokUrl` secret value match your *current* ngrok instance? If you're using the free version of ngrok, it changes the URL every time you restart it, so you have to update your secret to match. Use `dotnet user-secrets list` to see your current values.

**Comment by thomps0** [comment]
That's the weird part - I've always been getting 200 replies for the Notify function, (even when I first opened the issue) - 
![image](https://user-images.githubusercontent.com/45877444/119152630-7afb3200-ba1e-11eb-9875-cd5c47789bc5.png)

And from localhost:4040 - 
![image](https://user-images.githubusercontent.com/45877444/119152927-c1509100-ba1e-11eb-8754-03c2e2279e19.png)

I did make the mistake early on of copying the http instead of the https URL (well before opening this issue) and I am aware that I have to restart the function if I change the URL.

**Comment by jasonjoh** [comment]
I'm beginning to suspect this is more of a service issue. The response is exactly what it should be to validate, and it's responding in a timely fashion. Is there potentially anything between you and the internet which might be blocking the response from going out?

To be doubly sure I just tested this again and had no issues. My response to the validation request is identical to yours.

**Comment by thomps0** [comment]
Great thought... I'll have to spin this up on my personal machine where I have a bit more visibility and control over the AV/Firewall. It is VERY possible that our corp. AV is blocking this. I'll have to tackle this over the weekend. Thanks for the help on this and I'll update on Monday to see if I was able to resolve.
